#!/usr/bin/env node
/**
 * One-shot prober against a REAL Strava application.
 *
 *   node scripts/strava-probe.mjs            # full run, no deauthorize
 *   node scripts/strava-probe.mjs --deauth   # also probe POST /oauth/deauthorize (revokes!)
 *
 * Why this exists: network to developers.strava.com is blocked from the machine this app
 * was written on, so every Strava-specific fact in the code is knowledge rather than
 * documentation. The code is deliberately written to be correct under either reading of
 * each open question; this script is what turns the guesses into recorded answers.
 *
 * It resolves, in one sitting:
 *   1. the exact X-RateLimit-* / X-ReadRateLimit-* values (100/1000 or 200/2000?), and
 *      whether both pairs are even sent;
 *   2. whether per_page=200 is accepted or 400s;
 *   3. whether `before`/`after` compare start_date (UTC) or start_date_local;
 *   4. whether a second refresh returns a DIFFERENT refresh_token;
 *   5. the POST /oauth/deauthorize response shape;
 *   6. whether Retry-After appears at all.
 *
 * Secrets discipline: STRAVA_CLIENT_SECRET is never printed, and every token is
 * truncated to 6 characters. Everything written to stdout and to probe-output.json goes
 * through redact() first, so a pasted probe log cannot leak a live grant. That matters
 * more here than anywhere else in the tree: this is the one script whose whole output is
 * meant to be copied into a document.
 */
import { createInterface } from 'node:readline/promises';
import { stdin, stdout, argv, exit } from 'node:process';
import { writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';

import { loadConfig } from '../server/config.js';
import { buildAuthorizeUrl, redirectUri, assertScope } from '../server/strava/authUrl.js';
import { parseRateLimitHeaders } from '../server/strava/map.js';

const OUT_PATH = 'probe-output.json';
const WANT_DEAUTH = argv.includes('--deauth');

/** Values that must never appear in output, longest first so nesting redacts correctly. */
const secrets = new Set();

function redact(value) {
  if (typeof value === 'string') {
    let out = value;
    for (const s of [...secrets].sort((a, b) => b.length - a.length)) {
      if (s.length >= 6) out = out.split(s).join(`${s.slice(0, 6)}…[redacted]`);
    }
    return out;
  }
  if (Array.isArray(value)) return value.map(redact);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, redact(v)]));
  }
  return value;
}

/** Tokens are shown as 6 chars + a length, which is enough to tell two apart. */
function fingerprint(token) {
  if (typeof token !== 'string' || token === '') return null;
  return `${token.slice(0, 6)}…(${token.length} chars)`;
}

function say(...parts) {
  stdout.write(`${parts.map((p) => (typeof p === 'string' ? redact(p) : JSON.stringify(redact(p), null, 2))).join(' ')}\n`);
}

function rule(title) {
  say(`\n${'='.repeat(72)}\n${title}\n${'='.repeat(72)}`);
}

const results = {
  _readme: 'Generated by scripts/strava-probe.mjs. Secrets redacted, tokens truncated to 6 chars.',
  ranAt: new Date().toISOString(),
  answers: {},
  steps: [],
};

/**
 * Raw fetch, deliberately NOT going through server/strava/client.js.
 *
 * The client's whole job is to hide response headers and bodies; this script exists to
 * look at them, and probing reality through the abstraction under test would let a bug in
 * the abstraction masquerade as a fact about Strava.
 */
async function probeFetch(label, url, { method = 'GET', form = null, bearer = null } = {}) {
  const headers = { Accept: 'application/json' };
  if (bearer) headers.Authorization = `Bearer ${bearer}`;
  let body;
  if (form) {
    headers['Content-Type'] = 'application/x-www-form-urlencoded';
    body = new URLSearchParams(form).toString();
  }

  const started = Date.now();
  let response;
  try {
    response = await fetch(url, { method, headers, body, signal: AbortSignal.timeout(20_000) });
  } catch (err) {
    const step = { label, method, url: new URL(url).pathname, transportError: String(err?.message ?? err) };
    results.steps.push(step);
    say(`\n[${label}] TRANSPORT ERROR:`, String(err?.message ?? err));
    return { ok: false, status: 0, headers: {}, json: null, text: '' };
  }

  const text = await response.text();
  let json = null;
  try {
    json = JSON.parse(text);
  } catch {
    /* not JSON; the raw text is recorded instead */
  }

  // Verbatim header dump -- the primary artifact of this whole script.
  const headerDump = {};
  for (const [k, v] of response.headers) headerDump[k] = v;

  const step = {
    label,
    method,
    url: new URL(url).pathname + (new URL(url).search || ''),
    status: response.status,
    elapsedMs: Date.now() - started,
    headers: headerDump,
    rateLimit: parseRateLimitHeaders(response.headers),
    bodyKind: Array.isArray(json) ? `array(${json.length})` : (json ? 'object' : 'non-json'),
    bodyKeys: json && !Array.isArray(json) ? Object.keys(json) : null,
  };
  results.steps.push(step);

  say(`\n[${label}] ${method} ${new URL(url).pathname}${new URL(url).search} -> ${response.status} (${step.elapsedMs} ms)`);
  say('  headers:', headerDump);
  say('  rate-limit parsed:', step.rateLimit);
  if (json && !Array.isArray(json)) say('  body keys:', Object.keys(json));
  if (Array.isArray(json)) say(`  body: array of ${json.length}`);
  if (!json && text) say('  body (non-JSON, first 200 chars):', text.slice(0, 200));

  return { ok: response.status >= 200 && response.status < 300, status: response.status, headers: headerDump, json, text };
}

function loadOrDie() {
  try {
    return loadConfig(process.env, { loadEnvFile: true });
  } catch (err) {
    say('Could not load configuration:', String(err?.message ?? err));
    say('Run `npm run keygen`, copy .env.example to .env, and fill in STRAVA_CLIENT_ID / STRAVA_CLIENT_SECRET.');
    exit(1);
  }
}

async function main() {
  const config = loadOrDie();
  secrets.add(config.stravaClientSecret);

  if (config.stravaApiBase.includes('fake') || config.stravaOauthBase.includes('fake')) {
    say('Refusing to run: STRAVA_API_BASE/STRAVA_OAUTH_BASE point at the test double.');
    exit(1);
  }

  results.answers.apiBase = config.stravaApiBase;
  results.answers.oauthBase = config.stravaOauthBase;
  results.answers.redirectUri = redirectUri(config);

  const rl = createInterface({ input: stdin, output: stdout });
  try {
    // ---------------------------------------------------------------- 1. consent
    rule('STEP 1 -- authorize (manual, in a browser)');
    const state = randomBytes(16).toString('hex');
    const authorizeUrl = buildAuthorizeUrl(config, { state, approvalPrompt: 'force' });
    say('Open this URL, approve, and then copy the FULL URL your browser lands on');
    say(`(it will be a ${redirectUri(config)}?... URL that probably fails to load -- that is fine):\n`);
    say(authorizeUrl);
    say('\nNOTE: leave every scope checkbox CHECKED for this run. Re-run with one unchecked');
    say('later to confirm the ?scope= callback parameter really reflects the rider\'s choices.');

    const pasted = (await rl.question('\nPaste the callback URL (or just the code): ')).trim();
    let code = pasted;
    let grantedScope = null;
    if (pasted.includes('?') || pasted.startsWith('http')) {
      const u = new URL(pasted.startsWith('http') ? pasted : `http://localhost/${pasted}`);
      code = u.searchParams.get('code') ?? '';
      grantedScope = u.searchParams.get('scope');
      if (u.searchParams.get('state') !== state) {
        say('WARNING: the state parameter does not match what we sent. Continuing anyway (this is a probe).');
      }
    }
    if (!code) {
      say('No code found in what you pasted. Aborting.');
      exit(1);
    }
    secrets.add(code);

    results.answers.callbackScopeParamPresent = grantedScope !== null;
    results.answers.callbackScope = grantedScope;
    if (grantedScope) {
      results.answers.assertScopeResult = assertScope(grantedScope);
      say('\ncallback ?scope= :', grantedScope, '-> assertScope():', results.answers.assertScopeResult);
    } else {
      say('\nNo ?scope= in the callback (you pasted only the code), so scope semantics were not observed.');
    }

    // ---------------------------------------------------------------- 2. token exchange
    rule('STEP 2 -- POST /oauth/token (authorization_code)');
    const exchange = await probeFetch('token:authorization_code', `${config.stravaOauthBase}/token`, {
      method: 'POST',
      form: {
        client_id: config.stravaClientId,
        client_secret: config.stravaClientSecret,
        code,
        grant_type: 'authorization_code',
      },
    });
    if (!exchange.ok) {
      say('Token exchange failed; nothing further can be probed. (A code is single-use -- re-run from step 1.)');
      finish();
      return;
    }

    let accessToken = exchange.json.access_token;
    let refreshToken = exchange.json.refresh_token;
    secrets.add(accessToken);
    secrets.add(refreshToken);

    results.answers.tokenResponseKeys = Object.keys(exchange.json);
    results.answers.tokenResponseIncludesScope = 'scope' in exchange.json;
    results.answers.tokenResponseScope = exchange.json.scope ?? null;
    results.answers.tokenResponseIncludesAthlete = Boolean(exchange.json.athlete);
    results.answers.expiresAtPresent = 'expires_at' in exchange.json;
    say('\naccess_token:', fingerprint(accessToken));
    say('refresh_token:', fingerprint(refreshToken));
    say('token response keys:', results.answers.tokenResponseKeys);

    // ---------------------------------------------------------------- 3. athlete
    rule('STEP 3 -- GET /athlete (rate-limit headers on a read endpoint)');
    const athlete = await probeFetch('athlete', `${config.stravaApiBase}/athlete`, { bearer: accessToken });
    results.answers.athleteId = athlete.json?.id ?? null;
    results.answers.athleteProfileUrl = athlete.json?.profile ?? null;
    // The avatar CDN host is [UNVERIFIED] in the CSP; this is where it gets recorded.
    results.answers.avatarHost = athlete.json?.profile ? safeHost(athlete.json.profile) : null;
    results.answers.rateLimitHeadersPresent = {
      overall: 'x-ratelimit-limit' in athlete.headers,
      read: 'x-readratelimit-limit' in athlete.headers,
    };
    say('\navatar host (record this for the CSP img-src):', results.answers.avatarHost);

    // ---------------------------------------------------------------- 4. per_page
    rule('STEP 4 -- per_page=200 vs per_page=100');
    const p200 = await probeFetch('activities:per_page=200', `${config.stravaApiBase}/athlete/activities?per_page=200&page=1`, { bearer: accessToken });
    const p100 = await probeFetch('activities:per_page=100', `${config.stravaApiBase}/athlete/activities?per_page=100&page=1`, { bearer: accessToken });
    results.answers.perPage200Accepted = p200.status === 200;
    results.answers.perPage200Returned = Array.isArray(p200.json) ? p200.json.length : null;
    results.answers.perPage100Returned = Array.isArray(p100.json) ? p100.json.length : null;
    say('\nper_page=200 accepted:', String(results.answers.perPage200Accepted),
      '| returned:', String(results.answers.perPage200Returned),
      '| per_page=100 returned:', String(results.answers.perPage100Returned));
    say('ordering check (first vs last start_date of the 200-page):',
      Array.isArray(p200.json) && p200.json.length > 1
        ? `${p200.json[0].start_date} .. ${p200.json.at(-1).start_date}`
        : 'not enough activities to tell');
    results.answers.defaultOrdering = orderingOf(p200.json);

    // Ordering is documented as newest-first, but is believed to FLIP to ascending when
    // `after` is set -- which is why the watermark is a Math.max rather than a positional
    // read. Recording it here is cheap, and this page doubles as the oldest-rides pool
    // for step 5 (an athlete's most recent 200 rides may all share one timezone).
    const ascendingPage = await probeFetch(
      'activities:after=0 (ordering with `after` present)',
      `${config.stravaApiBase}/athlete/activities?per_page=200&page=1&after=0`,
      { bearer: accessToken },
    );
    results.answers.orderingWithAfter = orderingOf(ascendingPage.json);
    say('\nordering with `after` present:', results.answers.orderingWithAfter,
      '| without:', results.answers.defaultOrdering);

    // ---------------------------------------------------------------- 5. before/after semantics
    rule('STEP 5 -- do before/after compare start_date (UTC) or start_date_local?');
    const pool = [
      ...(Array.isArray(p200.json) ? p200.json : []),
      ...(Array.isArray(p100.json) ? p100.json : []),
      ...(Array.isArray(ascendingPage.json) ? ascendingPage.json : []),
    ];
    const probeRide = pickOffsetRide(pool);
    if (!probeRide) {
      say('No activity with a non-zero UTC offset was available, so this cannot be observed.');
      say('Upload (or wait for) one ride outside UTC and re-run just this step.');
      results.answers.beforeAfterSemantics = 'unobserved';
    } else {
      const utcEpoch = Math.floor(Date.parse(probeRide.start_date) / 1000);
      // start_date_local is a wall clock with a bogus Z; parsing it AS IF it were UTC is
      // exactly the "local interpretation" we are testing for.
      const localAsUtcEpoch = Math.floor(Date.parse(probeRide.start_date_local) / 1000);
      const offsetSeconds = localAsUtcEpoch - utcEpoch;
      say(`\nprobe ride ${probeRide.id}: start_date=${probeRide.start_date} start_date_local=${probeRide.start_date_local}`);
      say(`implied UTC offset: ${offsetSeconds} s (${(offsetSeconds / 3600).toFixed(1)} h)`);

      // Two windows, each of which includes the ride under exactly ONE interpretation.
      const between = (a, b) => `${config.stravaApiBase}/athlete/activities?per_page=200&after=${a}&before=${b}`;
      const utcOnly = offsetSeconds > 0
        ? between(utcEpoch - 60, localAsUtcEpoch - 60)
        : between(localAsUtcEpoch + 60, utcEpoch + 60);
      const localOnly = offsetSeconds > 0
        ? between(localAsUtcEpoch - 60, localAsUtcEpoch + 60)
        : between(utcEpoch + 60, utcEpoch + 120);

      const utcWindow = await probeFetch('after/before:UTC-only window', utcOnly, { bearer: accessToken });
      const localWindow = await probeFetch('after/before:local-only window', localOnly, { bearer: accessToken });
      const inUtc = Array.isArray(utcWindow.json) && utcWindow.json.some((a) => a.id === probeRide.id);
      const inLocal = Array.isArray(localWindow.json) && localWindow.json.some((a) => a.id === probeRide.id);

      results.answers.beforeAfterSemantics = inUtc && !inLocal
        ? 'start_date (UTC)'
        : (!inUtc && inLocal ? 'start_date_local' : `ambiguous (inUtcWindow=${inUtc}, inLocalWindow=${inLocal})`);
      results.answers.beforeAfterProbeRideId = probeRide.id;
      results.answers.beforeAfterOffsetSeconds = offsetSeconds;
      say('\nSEMANTICS:', results.answers.beforeAfterSemantics);
      say('Either answer is safe for this app: computeSyncMonths pads +/-86400 s, and no');
      say('UTC offset exceeds 14 h. This is recorded, not depended on.');
    }

    // ---------------------------------------------------------------- 6. refresh rotation
    rule('STEP 6 -- does refresh_token rotate? (two refreshes in a row)');
    const first = await probeFetch('token:refresh#1', `${config.stravaOauthBase}/token`, {
      method: 'POST',
      form: {
        client_id: config.stravaClientId,
        client_secret: config.stravaClientSecret,
        refresh_token: refreshToken,
        grant_type: 'refresh_token',
      },
    });
    let rotated1 = null;
    if (first.ok) {
      rotated1 = first.json.refresh_token !== refreshToken;
      say('\nrefresh #1: old', fingerprint(refreshToken), '-> new', fingerprint(first.json.refresh_token),
        rotated1 ? '(ROTATED)' : '(unchanged)');
      secrets.add(first.json.refresh_token);
      secrets.add(first.json.access_token);
      refreshToken = first.json.refresh_token;
      accessToken = first.json.access_token;
    }

    const second = await probeFetch('token:refresh#2', `${config.stravaOauthBase}/token`, {
      method: 'POST',
      form: {
        client_id: config.stravaClientId,
        client_secret: config.stravaClientSecret,
        refresh_token: refreshToken,
        grant_type: 'refresh_token',
      },
    });
    let rotated2 = null;
    if (second.ok) {
      rotated2 = second.json.refresh_token !== refreshToken;
      say('refresh #2: old', fingerprint(refreshToken), '-> new', fingerprint(second.json.refresh_token),
        rotated2 ? '(ROTATED)' : '(unchanged)');
      secrets.add(second.json.refresh_token);
      secrets.add(second.json.access_token);
      const supersededRefresh = refreshToken;
      refreshToken = second.json.refresh_token;
      accessToken = second.json.access_token;

      if (rotated2) {
        // The consequence that actually matters: is the superseded token dead? If it is,
        // "persist only if changed" is an unrecoverable lockout, not an optimization.
        const replay = await probeFetch('token:refresh#2 replay of superseded token', `${config.stravaOauthBase}/token`, {
          method: 'POST',
          form: {
            client_id: config.stravaClientId,
            client_secret: config.stravaClientSecret,
            refresh_token: supersededRefresh,
            grant_type: 'refresh_token',
          },
        });
        results.answers.supersededRefreshTokenStatus = replay.status;
        results.answers.supersededRefreshTokenBody = replay.json ? redact(replay.json) : null;
        say('replaying the superseded refresh token ->', String(replay.status));
      }
    }
    results.answers.refreshTokenRotates = rotated1 === null && rotated2 === null ? 'unobserved' : Boolean(rotated1 || rotated2);
    results.answers.refreshRotatedFirst = rotated1;
    results.answers.refreshRotatedSecond = rotated2;

    // ---------------------------------------------------------------- 7. deauthorize
    rule('STEP 7 -- POST /oauth/deauthorize');
    let doDeauth = WANT_DEAUTH;
    if (!doDeauth && stdin.isTTY) {
      const ans = (await rl.question('Probe deauthorize? This REVOKES the grant you just created. [y/N] ')).trim().toLowerCase();
      doDeauth = ans === 'y' || ans === 'yes';
    } else if (!doDeauth) {
      // Non-interactive stdin: never ask. A prompt nobody can answer hangs the run, and
      // silently defaulting to "yes" would revoke a grant the operator did not consent to.
      say('stdin is not a TTY, so the destructive step is skipped. Pass --deauth to force it.');
    }
    if (doDeauth) {
      const deauth = await probeFetch('deauthorize', `${config.stravaOauthBase}/deauthorize`, {
        method: 'POST',
        bearer: accessToken,
        form: { access_token: accessToken },
      });
      results.answers.deauthorizeStatus = deauth.status;
      results.answers.deauthorizeBodyKeys = deauth.json && !Array.isArray(deauth.json) ? Object.keys(deauth.json) : null;

      // Second call: the client treats a 401 here as success, so confirm what it really is.
      const again = await probeFetch('deauthorize (second call)', `${config.stravaOauthBase}/deauthorize`, {
        method: 'POST',
        bearer: accessToken,
        form: { access_token: accessToken },
      });
      results.answers.deauthorizeSecondStatus = again.status;
      say('\ndeauthorize:', String(results.answers.deauthorizeStatus),
        'keys:', results.answers.deauthorizeBodyKeys ?? 'n/a',
        '| second call:', String(results.answers.deauthorizeSecondStatus));
    } else {
      say('Skipped. Re-run with --deauth when you are willing to revoke the grant.');
      results.answers.deauthorizeStatus = 'unobserved';
    }
  } finally {
    rl.close();
  }

  finish();
}

function finish() {
  rule('SUMMARY -- the unverified ledger, resolved');
  say(results.answers);
  writeFileSync(OUT_PATH, `${JSON.stringify(redact(results), null, 2)}\n`);
  say(`\nWrote ${OUT_PATH} (gitignored). Secrets redacted, tokens truncated.`);
  say('Copy the answers block into docs/SPEC.md and delete the matching [UNVERIFIED] tags.');
}

function safeHost(url) {
  try {
    return new URL(url).host;
  } catch {
    return null;
  }
}

function orderingOf(list) {
  if (!Array.isArray(list) || list.length < 2) return 'unobserved';
  const first = Date.parse(list[0].start_date);
  const last = Date.parse(list.at(-1).start_date);
  if (first === last) return 'unobserved';
  return first > last ? 'descending (newest first)' : 'ascending';
}

/**
 * Pick the activity whose start_date and start_date_local disagree the most.
 *
 * A zero-offset (UTC) ride cannot distinguish the two interpretations at all, which is
 * why the probe hunts for the largest offset rather than taking the newest ride.
 */
function pickOffsetRide(list) {
  if (!Array.isArray(list)) return null;
  let best = null;
  let bestOffset = 0;
  for (const a of list) {
    if (typeof a?.start_date !== 'string' || typeof a?.start_date_local !== 'string') continue;
    const offset = Math.abs(Date.parse(a.start_date_local) - Date.parse(a.start_date));
    if (offset > bestOffset) {
      bestOffset = offset;
      best = a;
    }
  }
  return bestOffset >= 3_600_000 ? best : null;
}

await main();
